[package]
name = "chwowserver"
version = "0.1.0"
edition = "2024"
description = "CLI tool to quickly switch the realmlist.wtf of one or more World of Warcraft installations"

[[bin]]
name = "chwowserver"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.4.18", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "=0.8.8"
anyhow = "1"
dirs = "5"
indexmap = "=2.2.6"
